/**
 * Converts a side 2 yard line to a left to right cord from 50 to 100
 * @param {int} line 0 - 50
 * @returns 100 - 50
 */
const side2Convert = (line) => {
    return 100 - line;
}

const hashConvert = (useHash) => {
    if (useHash === "Front side") {
        return 1;
    }
    if (useHash === "Front Hash") {
        return 2/3;
    }
    if (useHash === "Back Hash"){
        return 1/3;
    }
    return 0;
}

/**
 * Convert Dot Object to Coordinates
 * @param {Object} dot 
 * @param {float} width 
 * @param {float} height 
 * @returns 
 */
const convertDotToCords = (dot, width, height) => {
    // Point to the new method
    return posFromBits(dot.dot_pos, width, height);
}

// NEW CONVERSIONS

/**
 * Position from bits
 * @param {int} binary - binary 29 bits representing the position information
 * @param {int} width
 * @param {int} height
 * @return cords in px
 */
const posFromBits = (binary, width, height) => {
    let bDir 		= parseInt(binary >>> 27);
    // let dir         = directionFromBits(bDir);

    let bLine 		= parseInt(binary % Math.pow(2, 27)) >>> 23;
    let line        = lineFromBits(bLine);

    let bSteps	 	= parseInt(binary % Math.pow(2, 23)) >>> 15;
    let steps       = stepsFromBits(bSteps);

    let bSide 		= parseInt(binary % Math.pow(2, 15)) >>> 14;
    let side        = sideFromBits(bSide);


    let bFBSteps	= parseInt(binary % Math.pow(2, 14)) >>> 4;
    let fbSteps     = stepsFromBits(bFBSteps);

    let bFBDir 		= parseInt(binary % Math.pow(2, 4)) >>> 2;
    // let fbDir       = fbDirFromBits(bFBDir);


    let bHash 		= parseInt(binary % Math.pow(2, 2));
    // let hash        = hashFromBits(bHash);

    const YARDS_IN_STEP = 0.625;
    const FT_IN_STEP = 1.875;

    // Default Direction Modifier to "OUTSIDE"
    let dModifier = -1;
    let sModifier = 0;
    let fbdModifier = 1;

    // "INSIDE"
    if (bDir === 1) {
        dModifier = 1;
    }
    // "ON"
    else if (bDir === 0) {
        dModifier = 0;
    }

    if (line !== 0) {
        // Side 1 is left
        if (side === 1) {
            sModifier = 1;
        } else {
            line  = side2Convert(line);
            sModifier = -1;
        }
    } else {
        // line = 50;
        sModifier = 0;
    }

    let relX = line + (dModifier * sModifier * steps * YARDS_IN_STEP);
    // Round to 2 decimals
    let x = Math.round(relX * width) / 100;

    // "BEHIND"
    if (bFBDir === 2) {
        fbdModifier = -1;
    } 
    // "ON"
    else if (bFBDir === 0) {
        fbdModifier = 0;
    }

    let hashY = bHashConvert(bHash);

    let oneStep = height / 1920 * 22.5;
    let relY = (fbdModifier * fbSteps * oneStep);
    let y = Math.round((height * hashY + relY) * 100) / 100;

    return {x: x, y: y};
}

/**
 * 
 * @param {int} bits 0-2
 * @returns direction string
 */
const directionFromBits = (bits) => {

    if (bits === 0) {
        return "On";
    }

    if (bits === 1) {
        return "Inside";
    }

    return "Outside";


}

/**
 * Line From Bits
 * @param {int} bits 0-10
 * @returns line (ie 5, 10..., 50)
 */
const lineFromBits = (bits) => {
    return bits * 5;
}

/**
 * Steps from bits
 * @param {int} binarySteps 8-10 bits, generated by stepsToBits() in backend
 * @returns steps
 */
const stepsFromBits = (binarySteps) => {
    let integer = binarySteps >>> 4;
    let decimal = binarySteps % 16;

    if (decimal === 1)
        return integer + 0.1;

    if (decimal === 2)
        return integer + 0.2;

    if (decimal === 3)
        return integer + 0.25;

    if (decimal === 4)
        return integer + 0.3;

    if (decimal === 5)
        return integer + 0.4;

    if (decimal === 6)
        return integer + 0.5;

    if (decimal === 7)
        return integer + 0.6;

    if (decimal === 8)
        return integer + 0.7;

    if (decimal === 9)
        return integer + 0.75;

    if (decimal === 10)
        return integer + 0.8;

    if (decimal === 11)
        return integer + 0.9;

    return integer;
}


/**
 * Side From Bits
 * @param {int} bits 0-1
 * @returns side 1-2
 */
const sideFromBits = (bits) => {
    return bits + 1;
}

/**
 * Forward-Backward Direction From Bits
 * @param {int} bits 0-3
 * @returns fb direction string
 */
const fbDirFromBits = (bits) => {
    if (bits === 0)
        return "On";
    
    if (bits === 1)
        return "Front";
    
    return "Behind";
}


/**
 * Hash From Bits
 * @param {int} bits 0-3
 * @returns hash string
 */
const hashFromBits = (bits) => {
    if (bits === 0)
        return "Front Side";
    
    if (bits === 1)
        return "Front Hash";
    
    if (bits === 2)
        return "Back Hash";
    
    return "Back Side";
}

/**
 * Binary Hash Convert
 * @param {int} bits 0-3
 * @returns 
 */
const bHashConvert = (bits) => {
    if (bits === 0) {
        return 1;
    }
    if (bits === 1) {
        return 2/3;
    }
    if (bits === 2){
        return 1/3;
    }
    return 0;
}




export default convertDotToCords;