from locust import HttpUser, task, between

class QuickstartUser(HttpUser):
    wait_time = between(1, 2)

    def on_start(self):
        pass
        # self.client.post("/login", json={"email":"mmiller5@ilstu.edu", "password":"fyhquz-dijfid-4Qommi"})

    @task
    def test_main_app(self):
        self.client.get("/sets?show_code=18UBYJYE&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDI2MSwianRpIjoiOTczMmRhMTktNTkxZS00MTIxLThmMDgtN2E4ZGRiMGJkZGE4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDI2MSwiZXhwIjoxNzIyMTgwNjYxfQ.pBJ0PWuPVA9NCeRUm1exZW5meB3CrMmg5I6l_xOyS5E")
        self.client.get("/get-dots?show_code=18UBYJYE&set=5&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDYyMiwianRpIjoiMzk1ODkyMGItYmJlNy00Mzg3LThhMDEtMDQxNGI2ODdlOGQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDYyMiwiZXhwIjoxNzIyMTgxMDIyfQ.srj5W9NvsMvDv-aJUi1R3LRlkO08DJSa-tbkkYaLOwI")
        self.client.get("/get-dots?show_code=18UBYJYE&set=12&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDYyMiwianRpIjoiMzk1ODkyMGItYmJlNy00Mzg3LThhMDEtMDQxNGI2ODdlOGQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDYyMiwiZXhwIjoxNzIyMTgxMDIyfQ.srj5W9NvsMvDv-aJUi1R3LRlkO08DJSa-tbkkYaLOwI")
        self.client.get("/get-dots?show_code=18UBYJYE&set=18&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDYyMiwianRpIjoiMzk1ODkyMGItYmJlNy00Mzg3LThhMDEtMDQxNGI2ODdlOGQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDYyMiwiZXhwIjoxNzIyMTgxMDIyfQ.srj5W9NvsMvDv-aJUi1R3LRlkO08DJSa-tbkkYaLOwI")
        self.client.get("/get-dots?show_code=18UBYJYE&set=24&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDYyMiwianRpIjoiMzk1ODkyMGItYmJlNy00Mzg3LThhMDEtMDQxNGI2ODdlOGQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDYyMiwiZXhwIjoxNzIyMTgxMDIyfQ.srj5W9NvsMvDv-aJUi1R3LRlkO08DJSa-tbkkYaLOwI")
        self.client.get("/get-dots?show_code=18UBYJYE&set=29&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDYyMiwianRpIjoiMzk1ODkyMGItYmJlNy00Mzg3LThhMDEtMDQxNGI2ODdlOGQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDYyMiwiZXhwIjoxNzIyMTgxMDIyfQ.srj5W9NvsMvDv-aJUi1R3LRlkO08DJSa-tbkkYaLOwI")
        self.client.get("/get-dots?show_code=18UBYJYE&set=35&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDYyMiwianRpIjoiMzk1ODkyMGItYmJlNy00Mzg3LThhMDEtMDQxNGI2ODdlOGQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDYyMiwiZXhwIjoxNzIyMTgxMDIyfQ.srj5W9NvsMvDv-aJUi1R3LRlkO08DJSa-tbkkYaLOwI")
        self.client.get("/get-dots?show_code=18UBYJYE&set=43&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDYyMiwianRpIjoiMzk1ODkyMGItYmJlNy00Mzg3LThhMDEtMDQxNGI2ODdlOGQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDYyMiwiZXhwIjoxNzIyMTgxMDIyfQ.srj5W9NvsMvDv-aJUi1R3LRlkO08DJSa-tbkkYaLOwI")
        self.client.get("/get-dots?show_code=18UBYJYE&set=49&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDYyMiwianRpIjoiMzk1ODkyMGItYmJlNy00Mzg3LThhMDEtMDQxNGI2ODdlOGQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDYyMiwiZXhwIjoxNzIyMTgxMDIyfQ.srj5W9NvsMvDv-aJUi1R3LRlkO08DJSa-tbkkYaLOwI")
        self.client.get("/get-dots?show_code=18UBYJYE&set=53&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjA5NDYyMiwianRpIjoiMzk1ODkyMGItYmJlNy00Mzg3LThhMDEtMDQxNGI2ODdlOGQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1taWxsZXI1QGlsc3R1LmVkdSIsIm5iZiI6MTcyMjA5NDYyMiwiZXhwIjoxNzIyMTgxMDIyfQ.srj5W9NvsMvDv-aJUi1R3LRlkO08DJSa-tbkkYaLOwI")
