"""added set name last update

Revision ID: 08cd33519f98
Revises: 183ee914288c
Create Date: 2023-06-13 14:36:03.036262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cd33519f98'
down_revision = '183ee914288c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_name', schema=None) as batch_op:
        batch_op.drop_column('last_update')

    # ### end Alembic commands ###
