"""prevented default null on is_default

Revision ID: 183ee914288c
Revises: 9cb72a7974b5
Create Date: 2023-06-08 09:08:57.139846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183ee914288c'
down_revision = '9cb72a7974b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_show')
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.create_table('_alembic_tmp_show',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('school_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=8), nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('last_update', sa.DATETIME(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
