"""moved to new update system

Revision ID: 1d5a3f0f178d
Revises: 251f97ff046d
Create Date: 2023-07-11 07:57:34.874016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5a3f0f178d'
down_revision = '251f97ff046d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('last_update',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('last_update',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
