"""added dot_icon

Revision ID: 21e157c9ee97
Revises: cac7d7b52522
Create Date: 2023-08-07 10:10:51.751704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e157c9ee97'
down_revision = 'cac7d7b52522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dot_icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('width_in_steps', sa.Integer(), nullable=True),
    sa.Column('hight_in_steps', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dot_icon_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('None', 'dot_icon', ['dot_icon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dot', schema=None) as batch_op:
        batch_op.drop_constraint('None', type_='foreignkey')
        batch_op.drop_column('dot_icon_id')

    op.drop_table('dot_icon')
    # ### end Alembic commands ###
