"""added varified date

Revision ID: 251f97ff046d
Revises: c7e0d6b4de3c
Create Date: 2023-06-26 21:51:05.741185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251f97ff046d'
down_revision = 'c7e0d6b4de3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verified_date')

    # ### end Alembic commands ###
