"""Added time codes to Set

Revision ID: 57cb07a00683
Revises: e479863bec30
Create Date: 2022-11-07 14:51:07.381774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cb07a00683'
down_revision = 'e479863bec30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('start_time_code', sa.Time(), nullable=True))
    op.add_column('set', sa.Column('end_time_code', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'end_time_code')
    op.drop_column('set', 'start_time_code')
    # ### end Alembic commands ###
