"""removed set name last update

Revision ID: c7e0d6b4de3c
Revises: 08cd33519f98
Create Date: 2023-06-13 14:39:26.761773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e0d6b4de3c'
down_revision = '08cd33519f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_name', schema=None) as batch_op:
        batch_op.drop_column('last_update')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
