"""added some new things

Revision ID: cac7d7b52522
Revises: e61dbd9565ea
Create Date: 2023-07-18 08:33:06.589344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac7d7b52522'
down_revision = 'e61dbd9565ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_counts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=256), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_admin_email', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('send_admin_email')

    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('total_counts')

    # ### end Alembic commands ###
