"""added set name versioning

Revision ID: e61dbd9565ea
Revises: 1d5a3f0f178d
Create Date: 2023-07-13 08:33:41.224191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61dbd9565ea'
down_revision = '1d5a3f0f178d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.Integer(), nullable=True))

    with op.batch_alter_table('dot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.Integer(), nullable=True))

    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.Integer(), nullable=True))

    with op.batch_alter_table('set_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.Integer(), nullable=True))

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_set_name_update', sa.Integer(), nullable=True))

    with op.batch_alter_table('show_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_user', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('last_set_name_update')

    with op.batch_alter_table('set_name', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('dot', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    with op.batch_alter_table('band_section', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('last_updated_date')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
