"""Added update tracking to 'show'

Revision ID: f4f3cf04fa45
Revises: 7e1a72a66695
Create Date: 2023-05-24 21:50:09.700231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f3cf04fa45'
down_revision = '7e1a72a66695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('last_update')

    # ### end Alembic commands ###
