"""added more things to show user

Revision ID: 7410689a054f
Revises: 88bfdfe9881c
Create Date: 2023-08-09 18:42:54.319181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7410689a054f'
down_revision = '88bfdfe9881c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_prop', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_stationary', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_user', schema=None) as batch_op:
        batch_op.drop_column('is_stationary')
        batch_op.drop_column('is_prop')

    # ### end Alembic commands ###
