"""added is_drum_major

Revision ID: e546819774e3
Revises: f4ce057e7008
Create Date: 2024-07-23 11:05:48.541003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e546819774e3'
down_revision = 'f4ce057e7008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_drum_major', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_user', schema=None) as batch_op:
        batch_op.drop_column('is_drum_major')

    # ### end Alembic commands ###
